### ISSUE TITLE
Update BSONCoder?

### ISSUE THREAD

**Issue by igr** [vexy/Fridge#53]
Got this warnings while building:
```
'NIOAtomic' is deprecated: please use ManagedAtomic from https://github.com/apple/swift-atomics instead
```

**Comment by vexy** [comment]
Yup, `SwiftNIO` changed some stuff under the hood. Will be updated in next version of `BSONCoder`.

**Comment by vexy** [comment]
`BSONCoder` updated to `v0.9`. Some build warnings have been removed but due to differences in Swift version, some of the warnings may still be present.

Check https://github.com/apple/swift-nio#repository-organization for more information.
